# Config file with all params
core:
    modelPath: /../App/Model
    controllerPath: /../App/Controller
    themePath: /../App/Theme
    filesPath: ./files
    maintenance: false
    devMode: true
    benchMark: true
    logEnabled: true
    templateCache: false
    cacheAutoReload: true
    defaultLang: 1
    forcedLang: false

app:
    theme: Default
    brandName: My company name
    randomVar: YYYYMMDD

cookies:
    cookieName: quaver
    cookieDomain: server
    cookiePath: /

db:
    hostname: localhost
    username: root
    password: root
    database: qv
    port: 3306
    devMode: true
    cypherKey: 12345678

folders:
    - cache
    - Ajax
    - files