# Basic
home:
    url: /
    controller: home
    action: home
    view: home

404:
    url: /404/
    controller: e404
    action: index
    view: e404

maintenance:
    url: /maintenance/
    controller: home
    action: maintenance
    view: maintenance

language:
    url: /language/([a-zA-Z0-9-_]+)?[/]?
    controller: language
    action: language
    view: none

# Auth
register:
    url: /register/
    controller: auth
    action: register
    view: register

login:
    url: /login/
    controller: auth
    action: login
    view: login

logout:
    url: /logout/
    controller: auth
    action: logout
    view: none

# Admin
admin:
    url: /admin/
    path: admin
    controller: dashboard
    action: home

admin_languages:
    url: /admin/languages/([a-zA-Z0-9-_]+)?[/]?([a-zA-Z0-9-_]+)?[/]?
    path: admin
    controller: dashboard
    action: languages

admin_users:
    url: /admin/users/([a-zA-Z0-9-_]+)?[/]?([a-zA-Z0-9-_]+)?[/]?
    path: admin
    controller: dashboard
    action: users

